name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Upload Maven build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bootdocker-jar
          path: target/bootdocker.jar

  docker_build:
    runs-on: ubuntu-latest
    needs: maven_build  # Ensure this job runs only after maven_build completes
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download Maven build artifacts
        uses: actions/download-artifact@v2
        with:
          name: bootdocker-jar
      - name: Build Docker image
        run: |
          IMAGE_NAME="sakthisiddu1/helloservice:${{ github.run_number }}"
          docker build -t $IMAGE_NAME .

  docker_push:
    runs-on: ubuntu-latest
    needs: docker_build  # Ensure this job runs only after docker_build completes
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        run: |
          IMAGE_NAME="sakthisiddu1/helloservice:${{ github.run_number }}"
          docker push $IMAGE_NAME
